name: DemoCDMain

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: ls -lah
      - run: id
      - run: sudo apt update -y
      - name: Upgrade
        run: sudo apt upgrade -y
  
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo DEPLOY PROD