name: learn-github-actions

on:
  push:
    branches: [ main ]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: sudo apt update -y
      - run: sudo apt upgrade -y